project_id = "gejgtkgqyzdfbsbxujgl"

[functions.create-checkout]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.trustpilot-proxy]
verify_jwt = false

[functions.process-abandoned-carts]
verify_jwt = false

[functions.send-config-email]

[functions.generate-store-image]
verify_jwt = false

[functions.project-store-on-photo]
verify_jwt = false

[functions.widget-chat]
verify_jwt = false

[functions.widget-save]
verify_jwt = false
