UPDATE configurator_settings SET data = '[
  {"id":"c_blanc","hex":"#F8F8F8","label":"Blanc","active":true,"type":"solid"},
  {"id":"c_vert_sapin","hex":"#1A4B3C","label":"Vert Sapin","active":true,"type":"solid"},
  {"id":"c_bleu_roi","hex":"#183E7A","label":"Bleu Roi","active":true,"type":"solid"},
  {"id":"c_orange_vif","hex":"#E55B13","label":"Orange Vif","active":true,"type":"solid"},
  {"id":"c_rouge_carmin","hex":"#A32020","label":"Rouge Carmin","active":true,"type":"solid"},
  {"id":"c_terre_cuite","hex":"#C67140","label":"Terre Cuite","active":true,"type":"solid"},
  {"id":"c_chocolat","hex":"#5C3A21","label":"Chocolat","active":true,"type":"solid"},
  {"id":"c_sable","hex":"#D2BCA2","label":"Sable","active":true,"type":"solid"},
  {"id":"c_bordeaux","hex":"#6E1E24","label":"Bordeaux","active":true,"type":"solid"},
  {"id":"c_noir","hex":"#111111","label":"Noir","active":true,"type":"solid"},
  {"id":"c_gris_souris","hex":"#8A8A8A","label":"Gris Souris","active":true,"type":"solid"},
  {"id":"c_taupe","hex":"#8B7D73","label":"Taupe","active":true,"type":"solid"},
  {"id":"c_bleu_ciel","hex":"#7B9ECE","label":"Bleu Ciel","active":true,"type":"solid"},
  {"id":"c_vert_olive","hex":"#6B7D3A","label":"Vert Olive","active":true,"type":"solid"},
  {"id":"c_turquoise","hex":"#4A9BA3","label":"Turquoise","active":true,"type":"solid"},
  {"id":"c_bleu_marine","hex":"#2A3654","label":"Bleu Marine","active":true,"type":"solid"},
  {"id":"t_gris_chine","hex":"#A9A9A9","label":"Gris Chiné","active":true,"type":"textured"},
  {"id":"t_anthracite","hex":"#3D3D3D","label":"Anthracite Texturé","active":true,"type":"textured"},
  {"id":"t_bleu_jean","hex":"#4C6A8D","label":"Bleu Jean","active":true,"type":"textured"},
  {"id":"r_jaune_blanc","hex":"#FFC300","label":"Rayé Jaune & Blanc","active":true,"type":"striped","colors":["#FFC300","#F8F8F8"]},
  {"id":"r_vert_blanc","hex":"#2E4F40","label":"Rayé Vert & Blanc","active":true,"type":"striped","colors":["#2E4F40","#F8F8F8"]},
  {"id":"r_bleu_blanc","hex":"#183E7A","label":"Rayé Bleu & Blanc","active":true,"type":"striped","colors":["#183E7A","#F8F8F8"]},
  {"id":"r_rouge_blanc","hex":"#A32020","label":"Rayé Rouge & Blanc","active":true,"type":"striped","colors":["#A32020","#F8F8F8"]},
  {"id":"r_gris_blanc","hex":"#8A8A8A","label":"Rayé Gris & Blanc","active":true,"type":"striped","colors":["#8A8A8A","#F8F8F8"]},
  {"id":"r_taupe_blanc","hex":"#8B7D73","label":"Rayé Taupe & Blanc","active":true,"type":"striped","colors":["#8B7D73","#F8F8F8"]},
  {"id":"r_bleu_gris","hex":"#4C6A8D","label":"Rayé Bleu & Gris","active":true,"type":"striped","colors":["#4C6A8D","#8A8A8A"]},
  {"id":"r_vert_gris","hex":"#5D7A68","label":"Rayé Vert & Gris","active":true,"type":"striped","colors":["#5D7A68","#A9A9A9"]},
  {"id":"r_multicolore_chaud","hex":"#E55B13","label":"Rayé Multicolore Chaud","active":true,"type":"striped","colors":["#E55B13","#C67140"]}
]'::jsonb WHERE id = 'toileColors';